services:
  ecoflow-bot:
    build: .
    container_name: ecoflow-bot
    environment:
      - ECOFLOW_PORTAL_URL=https://user-portal.ecoflow.com/user/eu/de/login
      - ECOFLOW_EMAIL=MAILADRESSE
      - ECOFLOW_PASSWORD=PASSWORT
      - HEALTHCHECK_URL=https://example.com/trigger
      - HEALTHCHECK_INTERVAL_MIN=5
      - SCREENSHOT_RETENTION_DAYS=5
    volumes:
      - ecoflow-bot:/app
    restart: unless-stopped

volumes:
  ecoflow-bot:
    external: true
